### ISSUE TITLE
No wireless debugging

### ISSUE THREAD

**Issue by secchipietro04** [tytydraco/LADB#28]
(not a problem, i'm just helping)
my phone is a samsung galaxy m20 with original android 10 and UI 2.0 so it doesn't have wireless debug option in developer mode, i don't know if this work in other phones but in probably every samsung phone with android 10 or above this works.
just connect phone with cable to the computer and connect to adb and type
```
adb tcpip 5555 
```
and eventually will print
```
restarting in TCP mode port: 5555
```
and
```
adb connect [phone local ip]
```
then open ladb, grant debug access and unplug the cable, it will works even if not connected to wifi but if you reboot or turn off the phone you will have to redo the steps

**Comment by teou1** [comment]
Well this is the standart tcp method on all android vesions till 10. Of course it works, it is just not so convenient.

Your problem is that you have android 10 and the new wireless debugging without any cables appears (sorry not sure) either in some very very last patch  update of A10, or in some beta in Android 11.

Officially is introduced in A11, so you just do not have it. But good to know the old workaround works with ladb app.

**Comment by hassanmush** [comment]
a4b24663663f980d45e0154d6f5bc7b0756df642

**Comment by gonza677** [comment]
adb shell settings put global hidden_api_policy_p_apps 1
